### ISSUE TITLE
Cannot find eigen_patch

### ISSUE THREAD

**Issue by guihomework** [RCPRG-ros-pkg/common_controllers#8]
Dear Maintainers, 
is this eigen_patch package available somewhere  ?
it is a dependency to this package and I could not find through a search in your organization (but sometimes git search is not so good)

we are interested in testing your cartesian trajectory (actionlib + interpolator) and were pretty happy already with some of your other controllers (orocos_controllers).

thanks in advance

**Comment by mjbogusz** [comment]
The `master` branch was stale and had some problems, including one you've noticed.
As the development happens on the `safe-controller` branch, I've changed it to be the default one.
